spring:
  application:
    name: suppliers
  datasource:
    url: jdbc:postgresql://localhost:54321/storage
    password: password
    driver-class-name: org.postgresql.Driver
    username: user


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true